# Generated by Django 3.0.6 on 2020-05-15 17:42

import Apps.Reproduccion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reproduccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('duracion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField()),
                ('foto', models.ImageField(upload_to=Apps.Reproduccion.models.images_path)),
            ],
        ),
    ]
