# Generated by Django 3.0.6 on 2020-05-15 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reproduccion', '0002_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reproduccion.Album'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='duracion',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
