# Generated by Django 3.0.6 on 2020-05-31 04:51

import Apps.Reproduccion.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reproduccion', '0002_album_artista'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='archivo',
            field=models.FileField(default=1, upload_to=Apps.Reproduccion.models.cancion_directory, validators=[django.core.validators.FileExtensionValidator(['mp3'])]),
            preserve_default=False,
        ),
    ]
