# Generated by Django 3.0.6 on 2020-05-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reproduccion', '0003_cancion_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
