# Generated by Django 3.0.6 on 2020-05-20 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reproduccion', '0004_disquera_generos_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistCanciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reproduccion.Cancion')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reproduccion.Playlist')),
            ],
        ),
    ]
