# Generated by Django 3.0.6 on 2020-05-20 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reproduccion', '0006_auto_20200519_2115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Generos',
            new_name='Genero',
        ),
    ]
