# Generated by Django 3.0.6 on 2020-05-20 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reproduccion', '0007_auto_20200519_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='disquera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reproduccion.Disquera'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reproduccion.Genero'),
            preserve_default=False,
        ),
    ]
