# Generated by Django 3.0.6 on 2020-05-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reproduccion', '0008_auto_20200519_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancion',
            options={'verbose_name': 'Cancion', 'verbose_name_plural': 'Canciones'},
        ),
        migrations.AlterModelOptions(
            name='playlistcanciones',
            options={'verbose_name': 'PlaylistCanciones', 'verbose_name_plural': 'PlaylistCanciones'},
        ),
        migrations.AlterModelOptions(
            name='usuariocanciones',
            options={'verbose_name': 'UsuarioCanciones', 'verbose_name_plural': 'UsuarioCanciones'},
        ),
        migrations.AlterField(
            model_name='disquera',
            name='descripcion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
