# Generated by Django 3.0.6 on 2020-05-30 22:36

import Apps.Usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_auto_20200522_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=Apps.Usuarios.models.user_directory_path),
        ),
    ]
